# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.srcs/sources_1/ip/clk_wiz_AD/clk_wiz_AD.xci
# IP: The module: 'clk_wiz_AD' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/clk_wiz_AD/clk_wiz_AD_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_AD'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/clk_wiz_AD/clk_wiz_AD.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_AD'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/clk_wiz_AD/clk_wiz_AD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_AD'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.srcs/sources_1/ip/clk_wiz_AD/clk_wiz_AD.xci
# IP: The module: 'clk_wiz_AD' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/clk_wiz_AD/clk_wiz_AD_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_AD'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/clk_wiz_AD/clk_wiz_AD.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_AD'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/clk_wiz_AD/clk_wiz_AD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_AD'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
