# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.srcs/sources_1/ip/CLK_GEN/CLK_GEN.xci
# IP: The module: 'CLK_GEN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/CLK_GEN/CLK_GEN_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_GEN'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/CLK_GEN/CLK_GEN.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_GEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/CLK_GEN/CLK_GEN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_GEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.srcs/sources_1/ip/CLK_GEN/CLK_GEN.xci
# IP: The module: 'CLK_GEN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/CLK_GEN/CLK_GEN_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_GEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/CLK_GEN/CLK_GEN.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_GEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/CLK_GEN/CLK_GEN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CLK_GEN'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
