# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.srcs/sources_1/ip/sqrt24/sqrt24.xci
# IP: The module: 'sqrt24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/sqrt24/sqrt24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt24'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.srcs/sources_1/ip/sqrt24/sqrt24.xci
# IP: The module: 'sqrt24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/sqrt24/sqrt24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt24'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
