# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.srcs/sources_1/ip/square_12_12/square_12_12.xci
# IP: The module: 'square_12_12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/square_12_12/square_12_12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_12_12'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.srcs/sources_1/ip/square_12_12/square_12_12.xci
# IP: The module: 'square_12_12' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/xie/Desktop/SW_TETS/SW_TETS/SW_TETS.gen/sources_1/ip/square_12_12/square_12_12_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_12_12'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
